export const BUCKET = 'imageprotocol'
export const CONFIG_PATH_CCPOLYGON = 'customerclass-polygon'
export const CONFIG_PATH_CC = 'customerclass'
export const CONFIG_PATH_POLYGON = 'polygon'
export const POLYGON_PRIORITY_SETTING = 'polygonPriority'
export const CUSTOMER_CLASS_PRIORITY_SETTING = 'customerClassPriority'
